CREATE TABLE malicious_web (
    URL TEXT PRIMARY KEY,
    URL_LENGTH INT,
    NUMBER_SPECIAL_CHARACTERS INT,
    CHARSET TEXT,
    SERVER TEXT,
    CONTENT_LENGTH INT,
    WHOIS_COUNTRY TEXT,
    WHOIS_STATEPRO TEXT,
    WHOIS_REGDATE VARCHAR(255),
    WHOIS_UPDATED_DATE VARCHAR(255),
    TCP_CONVERSATION_EXCHANGE INT,
    DIST_REMOTE_TCP_PORT INT,
    REMOTE_IPS INT,
    APP_BYTES INT,
    SOURCE_APP_PACKETS INT,
    REMOTE_APP_PACKETS INT,
    SOURCE_APP_BYTES INT,
    REMOTE_APP_BYTES INT,
    APP_PACKETS INT,
    DNS_QUERY_TIMES INT,
    TYPE INT
);

ALTER TABLE malicious_web OWNER TO postgres;

CREATE INDEX idx_URL ON malicious_web(URL);